version: "3.8"

services:
  react:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app

  backend:
    build:
      context: ./backend
    restart: "no"
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=myProjectDB
      - DB_USERNAME=myuser
      - DB_PASSWORD=mypassword
    working_dir: /var/www/html
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    depends_on:
      - mysql
    networks:
      - app
      - db

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    container_name: mysql
    environment:
      MYSQL_DATABASE: myProjectDB
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
    ports:
      - "8443:80"
    networks:
      - db

volumes:
  mysql:

networks:
  app:
    driver: bridge
  db:
    driver: bridge
